### ISSUE TITLE
Removed files

### ISSUE THREAD

**Issue by RickBioInf** [Amonith/mattermost-file-list#21] opened 2020-03-30 10:45 UTC
The deleted files are still findable with this plugin.

Again, great plugin.

**Comment by bbodenmiller** [comment] 2020-04-25 01:36
Not able to replicate myself.

**Comment by Amonith** [comment] 2020-04-26 14:08
Same, I have `IsDeleted = 0` filters in queries so it should work unless there are some cases where deleting posts does not delete files themselves or something like that.
@RickBioInf please provide more details.

**Comment by RickBioInf** [comment] 2020-04-28 10:49
Where is this `IsDeleted` parameter? I can't find it in either the config.json or the UI for administrators.

To provide a little more details:

1.  I uploaded an image in a message;
2.  I removed the message with the image in it;
3.  I used file-list and found the image.

**Comment by Tragen** [comment] 2020-04-28 10:52
For me, the files are not listed anymore but are still on disk.

**Comment by Amonith** [comment] 2020-04-28 11:07
@RickBioInf With `IsDeleted` I meant something internal in code (I'm the author of the plugin). I filter out files which MM marks as deleted as it doesn't delete files physically. Interestingly enough I cannot reproduce your scenario. Perhaps you have other plugins / configuration that interferes with deleting files?

@Tragen That is correct. MM does not delete files in community edition. In Enterprise Edition with Data Retention Policies you can set for how long deleted data should be kept.
Probably there are plugins which bring that feature to CE, but this won't be handled in this plugin.
The "Delete" feature in this plugin simply deletes the post exactly how the user would do it.

**Comment by Amonith** [comment] 2020-06-05 19:22
Closing the issue for now as no bug was found and the issue can't be replicated.

**Closed by Amonith** 2020-06-05 19:22 UTC
