### ISSUE TITLE
Failed to enable the plugin

### ISSUE THREAD

**Issue by qykong** [Amonith/mattermost-file-list#3] opened 2019-08-29 06:57 UTC
Hi, thanks for developing this plugin and it looks helpful. However, I tried to install the plugin but got an error message when enabling. We are currently on Mattermost v5.14.0 and deployed with matter-docker in production.

When I tried to enable the plugin, it gives the following error message from the system log:

```
Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
unable to start plugin: mattermost-file-list
github.com/mattermost/mattermost-server/plugin.(*Environment).Activate
        /go/src/github.com/mattermost/mattermost-server/plugin/environment.go:259
github.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState
        /go/src/github.com/mattermost/mattermost-server/app/plugin.go:96
github.com/mattermost/mattermost-server/app.(*App).InitPlugins
        /go/src/github.com/mattermost/mattermost-server/app/plugin.go:127
github.com/mattermost/mattermost-server/app.(*Server).RunOldAppInitalization.func6
        /go/src/github.com/mattermost/mattermost-server/app/server_app_adapters.go:147
github.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1
        /go/src/github.com/mattermost/mattermost-server/config/emitter.go:35
sync.(*Map).Range
        /usr/local/go/src/sync/map.go:333
github.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners
        /go/src/github.com/mattermost/mattermost-server/config/emitter.go:33
github.com/mattermost/mattermost-server/config.(*commonStore).set
        /go/src/github.com/mattermost/mattermost-server/config/common.go:90
github.com/mattermost/mattermost-server/config.(*FileStore).Set
        /go/src/github.com/mattermost/mattermost-server/config/file.go:97
github.com/mattermost/mattermost-server/app.(*App).SaveConfig
        /go/src/github.com/mattermost/mattermost-server/app/config.go:378
github.com/mattermost/mattermost-server/app.(*App).EnablePlugin
        /go/src/github.com/mattermost/mattermost-server/app/plugin.go:320
github.com/mattermost/mattermost-server/api4.enablePlugin
        /go/src/github.com/mattermost/mattermost-server/api4/plugin.go:252
github.com/mattermost/mattermost-server/web.Handler.ServeHTTP
        /go/src/github.com/mattermost/mattermost-server/web/handlers.go:144
github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1
        /go/src/github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler/gzip.go:336
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:1995
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
        /go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:212
github.com/mattermost/mattermost-server/app.(*RateLimiter).RateLimitHandler.func1
        /go/src/github.com/mattermost/mattermost-server/app/ratelimit.go:109
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:1995
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2774
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1878
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337>
```

**Comment by Amonith** [comment] 2019-08-29 07:29
Hi,

Interesting. What is"matter-docker"? Couldn't find anything in google.
Also what kind of OS hosts MM inside that image?

In environments known to me this plugin is currently working on following configurations:
- "mattermost-preview" docker image (5.13, 5.14.0), with MySQL database
- On-premise 5.12 mattermost with PostgreSQL
- On-premise 5.14.0 with PostgreSQL

**Comment by Amonith** [comment] 2019-08-29 07:39
Hmm, during activation I read the "config.json" to get the database connection string. Maybe that fails.
Is anything non-standard in how your MM is configured?

**Comment by qykong** [comment] 2019-08-29 23:07
Hi, thanks for the reply. Sorry, my bad. it was "mattermost-docker" projected maintained by mattermost team. 

I don't remember changing any configurations in "config.json", but I might be wrong. Is there anything I can do from my side to help get better error messages and nail down the issue?

**Comment by Amonith** [comment] 2019-08-30 07:06
Hi,

In "mattermost-docker" I can see that you can change the path to the config file through MM_CONFIG environment variable. Can you confirm that on your side indeed it is set to something other than default (`/mattermost/config/config.json`)?

If that's true, then I should be able to fix this today/tomorrow. If not, I think I will have to make a new release with better logging which you would have to install and through that we would be able to pinpoint the exact issue.

Today I will try to replicate your environment on my side. Since you're using docker it shouldn't take too long.

Thank you for your willingness to help, much appreciated!

**Comment by Amonith** [comment] 2019-08-30 07:10
Oh, just got an idea how you can help me further:
Can you anonymize (if there is anything confidential there) and share your `docker-compose.yaml`? That would allow me to replicate your environment 1:1.

**Comment by qykong** [comment] 2019-08-30 07:31
Hi, I can confirm the `docker-compose.yaml` I'm using is the same as [this](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml). For the config.json, you are right, I did change the setting a bit (the timezone setting and the `ServiceSettings.ListenAddress `).

Btw, I changed logging setting to DEBUG and got some new log messages. Are these more helpful?
```
{"level":"debug","ts":1567148486.9262085,"caller":"plugin/hclog_adapter.go:33","msg":"plugin started","plugin_id":"mattermost-file-list","wrapped_extras":"pathplugins/mattermost-file-list/server/dist/plugin-linux-amd64pid31943"}
{"level":"debug","ts":1567148486.92635,"caller":"plugin/hclog_adapter.go:33","msg":"waiting for RPC address","plugin_id":"mattermost-file-list","wrapped_extras":"pathplugins/mattermost-file-list/server/dist/plugin-linux-amd64"}
{"level":"debug","ts":1567148486.9268713,"caller":"plugin/hclog_adapter.go:35","msg":"Error relocating plugins/mattermost-file-list/server/dist/plugin-linux-amd64: __vfprintf_chk: symbol not found","plugin_id":"mattermost-file-list"}
{"level":"debug","ts":1567148486.927165,"caller":"plugin/hclog_adapter.go:35","msg":"Error relocating plugins/mattermost-file-list/server/dist/plugin-linux-amd64: __fprintf_chk: symbol not found","plugin_id":"mattermost-file-list"}
{"level":"warn","ts":1567148486.9274626,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"mattermost-file-list"}
{"level":"debug","ts":1567148486.9277148,"caller":"plugin/hclog_adapter.go:33","msg":"plugin process exited","plugin_id":"mattermost-file-list","wrapped_extras":"pathplugins/mattermost-file-list/server/dist/plugin-linux-amd64pid31943errorexit status 127"}
```

**Comment by js-everts** [comment] 2019-08-31 12:48
Hi, I have the exact same environment and was facing the same issue. I managed to fix it by compiling `mattermost-file-list` on alpine linux. @qykong your last comment was extremely helpful.

**Comment by qykong** [comment] 2019-08-31 12:59
That's awesome. Thanks for fixing that. Does that mean I could just download the latest compiled version and it will work?

**Comment by js-everts** [comment] 2019-08-31 13:11
No. you will have to compile it yourself. Or wait for @Amonith to release a version compiled on alpine (Although I'm not sure if this is something that makes much sense to do).

BTW I used the `golang:alpine` image to compile the plugin.

**Comment by qykong** [comment] 2019-08-31 13:14
> No. you will have to compile it yourself. Or wait for @Amonith to release a version compiled on alpine (Although I'm not sure if this is something that makes much sense to do).
> 
> BTW I used the `golang:alpine` image to compile the plugin.

Oops, sry, I thought the reply was from Amonith. Thanks, I'll do that!

**Comment by Amonith** [comment] 2019-08-31 21:49
Thanks @js-everts for help with this! I will release a recompiled version on monday along with a new sorting feature.

**Comment by Amonith** [comment] 2019-09-02 16:37
Status update:

This issue sparked a discussion in official Mattermost community server:
https://community.mattermost.com/core/pl/s8dh3p5xibyeicfge17a7ca1eo

and it seems that they were not aware that their docker images are not compatible with most plugins out of the box. They are considering modyfying the docker images in mattermost-docker, because this issue can also supposedly be solved by adding this to the dockerfile:

```
RUN apk add --no-cache libc6-compat
```

I'll keep the issue open for now and see where it goes.

**Comment by js-everts** [comment] 2019-09-03 13:08
I strongly agree that this issue is best tackled in the official mattermost docker images and not in individual plugins. Otherwise we burden plugin authors to compile and distribute multiple versions of the same plugin.

**Comment by ali-farooq0** [comment] 2019-09-26 14:41
@js-everts @Amonith @qykong  I'm from the Mattermost team and looking at fixing the issue above. It looks like the `mattermost-docker` image does install the `libc6-compat` lib as seen [here](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile#L19), so if you were to use mattermost-docker image to compile it should theoretically work. Wondering if that should address the concern here?

**Comment by ali-farooq0** [comment] 2019-09-26 16:24
@qykong are you using mattermost-docker file [here](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile)? or just using the docker compose [file](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) along with an alpine build?

**Comment by qykong** [comment] 2019-09-26 22:42
> @qykong are you using mattermost-docker file [here](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile)? or just using the docker compose [file](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) along with an alpine build?

Hi @ali-farooq0 , sorry that I didn't quite understand your questions. But I just followed the steps in the [readme](https://github.com/mattermost/mattermost-docker/blob/master/README.md) to set up the production environment, so I'm assuming I'm using both files?

**Comment by ali-farooq0** [comment] 2019-10-01 03:35
> > @qykong are you using mattermost-docker file [here](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile) [](/mattermost/mattermost-docker/blob/HEAD@{2019-09-26T22:42:47Z}/app/Dockerfile)? or just using the docker compose [file](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) [](/mattermost/mattermost-docker/blob/HEAD@{2019-09-26T22:42:47Z}/docker-compose.yml) along with an alpine build?
> 
> Hi @ali-farooq0 , sorry that I didn't quite understand your questions. But I just followed the steps in the [readme](https://github.com/mattermost/mattermost-docker/blob/master/README.md) [](/mattermost/mattermost-docker/blob/HEAD@{2019-09-26T22:42:47Z}/README.md) to set up the production environment, so I'm assuming I'm using both files?

@qykong Ah yes. In which case it should've worked out of the box 🤔. Are you currently blocked by the issue or have it resolved in another way?

**Comment by qykong** [comment] 2019-10-01 04:02
> 
> 
> > > @qykong are you using mattermost-docker file [here](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile) ? or just using the docker compose [file](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml)  along with an alpine build?
> > 
> > 
> > Hi @ali-farooq0 , sorry that I didn't quite understand your questions. But I just followed the steps in the [readme](https://github.com/mattermost/mattermost-docker/blob/master/README.md)  to set up the production environment, so I'm assuming I'm using both files?
> 
> @qykong Ah yes. In which case it should've worked out of the box 🤔. Are you currently blocked by the issue or have it resolved in another way?

Hi @ali-farooq0 , I was blocked by the issue but I resolved it after compiling it myself as the comment from @js-everts quoted below

> Hi, I have the exact same environment and was facing the same issue. I managed to fix it by compiling mattermost-file-list on alpine linux. @qykong your last comment was extremely helpful.

**Comment by ali-farooq0** [comment] 2019-10-08 13:46
@Amonith I'm able to reproduce the issue locally now using the latest mattermost--docker image.

What did you use to build your plugin? i.e. which container-image did you use to build your plugin here: https://github.com/Amonith/mattermost-file-list/releases/download/v0.5/mattermost-file-list-0.5.0.tar.gz

**Comment by Amonith** [comment] 2019-10-08 14:05
@ali-farooq0 none to be honest. I used raw Ubuntu 18.04 on my host machine, installed Go and nodejs and the rest of the dependencies was handled thanks to build scripts in:

https://github.com/mattermost/mattermost-plugin-starter-template

If using an alpine docker container solves it and doesn't break the plugin on non-alpine systems then I'll just adjust my workflow, but imho it should be then mentioned here:

https://developers.mattermost.com/extend/plugins/

**Comment by ali-farooq0** [comment] 2019-10-08 17:48
@Amonith interesting, I just tried building using a ubuntu docker image and even though it's dynamically linked, I was able to successfully activate the plugin. Wondering if you can post the output of `go env` here?

```
root@11cac7e6ef16:/home/workspace/go/src/github.com/mattermost-file-list# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/workspace/go/src/github.com/mattermost-file-list/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build603417358=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Amonith** [comment] 2019-10-08 17:58
@ali-farooq0 Sure, take a look at my (soft)wares:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mksondej/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mksondej/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/e/Dev/Projects/Mattermost/mattermost-file-list/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build384006226=/tmp/go-build -gno-record-gcc-switches"
```

```
mksondej@AMON-PC:/mnt/e/Dev/Projects/Mattermost/mattermost-file-list$ file dist/mattermost-file-list/server/dist/plugin-linux-amd64
dist/mattermost-file-list/server/dist/plugin-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, not stripped
```

Looks pretty similar to me. 
The only difference is that I am not using docker and that Ubuntu 18.04 is on WSL.

**Comment by ali-farooq0** [comment] 2019-10-18 15:23
@Amonith I created a Win-10 VM (virtualbox) and built a binary using WSL for the plugin and was **not** able to reproduce the issue. So it feels this issue is unique to your environment. Do you mind running `ldd --version` and share the output? Want to confirm the `glibc` version running on your WSL. If the versions are not the same do you mind updating `apt-get update; apt-get install libc6` and building the tar again?

My ubuntu docker + WSL output are the same:
```
ali@DESKTOP-IUMTB06:~/workspace/go/src/github.com/mattermost-file-list$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

ali@DESKTOP-IUMTB06:~/workspace/go/src/github.com/mattermost-file-list$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
ali@DESKTOP-IUMTB06:~/workspace/go/src/github.com/mattermost-file-list$
```

**Comment by Amonith** [comment] 2019-10-23 19:57
@ali-farooq0 unfortunately my output is identical.
I'm learning how to do the build entirely through Docker as we speak, so let's just assume that the issue will be solved. Upcoming releases will be built using a new pipeline.

**Comment by ali-farooq0** [comment] 2019-10-23 20:06
😢 Alright, mind sharing the tar file built through the new pipeline, i'll test it out on the prod-mm docker container.

**Comment by Amonith** [comment] 2019-10-28 19:59
Hi @ali-farooq0,

I cobbled up that Docker build pipeline. You can see how it works from the latest commits. Seems to do its job.

Here is the built plugin:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.5.1

I would be grateful for that check on the prod-mm container :)

**Comment by ali-farooq0** [comment] 2019-10-28 23:50
@Amonith I just gave it a try and it worked on the prod-mm container! 👍 Does it work on your WSL ubuntu set up? If so, looks like your new pipeline is working well 🎉

**Comment by Amonith** [comment] 2019-10-29 08:07
@ali-farooq0 Awesome! Much appreciated :)
Yes, it seems to work everwhere, including my dev machine and our company's dedicated ubuntu server.
Finally I can close the ticket :)

@qykong @js-everts From now on I will release builds compatible with Alpine thanks to the new pipeline. Again thank you all for help :)

**Closed by Amonith** 2019-10-29 08:07 UTC
